### ISSUE TITLE
Unicode column values are corrupted

### ISSUE THREAD

**Issue by alainbryden** [aws/amazon-redshift-odbc-driver#24]
## Version
 - Driver version: `2.1.3.0`
 - Redshift version `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.71629`
 - Client Operating System: `Windows Server 2019`

## Problem description
When upgrading from driver version 1.5.9 -> 2.1.3, I saw that unicode strings were not coming through correctly. The old driver installer had a configuration item to enable or disable unicode support:
![image](https://github.com/user-attachments/assets/dd0a5f97-fc74-4f8d-96ff-0708be06c1ac)

But this new driver has no such option.

I have the following test which I ran before and after the upgrade:
```
SELECT * FROM OPENQUERY([REDSHIFT], 'SELECT ''ぬるを'' AS UnicodeTest_openquery')
EXEC('SELECT ''ぬるを'' AS UnicodeTest_exec') AT [REDSHIFT]
```

On version 1.5.9, this returns the expected result:
```
るを_unicodetest_openquery
ぬるを
るを_unicodetest_exec
ぬるを
```
![image](https://github.com/user-attachments/assets/c14a55b7-4b48-42ee-9e85-cbea92d103be)

On 2.1.3, the column names survive, but the values are mangled:
```
るを_unicodetest_openquery
ã¬ã‚‹ã‚’
るを_unicodetest_exec
ã¬ã‚‹ã‚’
```
![image](https://github.com/user-attachments/assets/31071875-1556-4951-8d6e-d2e03511fa05)

We were upgrading to hopefully take advantage of ZSTD compression, but we use global datasets, so this regression is holding us back.

**Comment by vahid110** [comment]
Hi @alainbryden 
Thank you for taking the time to report this issue. I appreciate your effort and will make sure it reaches the appropriate team for investigation as soon as possible.

**Comment by vahid110** [comment]
@alainbryden 
After discussing with my team, it turns out we have to extend our driver to support this feature. I will keep this ticket open for further updates.
Thanks

**Comment by vahid110** [comment]
Hi @TillBender23  This fix was released into v2.1.15.0 and 2.1.16.0. Public docs are being updated with download links to public S3:
https://s3.amazonaws.com/redshift-downloads/drivers/odbc/2.1.16.0/AmazonRedshiftODBC64-2.1.16.0.msi

Thank you for your patience. Please let me know if it resolves your issue.

**Comment by TillBender23** [comment]
Hi @vahid110, the fix resolves the unicode issues. Thank you!

However we are still experiencing an issue described in [issue 37](https://github.com/aws/amazon-redshift-odbc-driver/issues/37)
